// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8RQzJHNi8pUmqiAYcUrFU5sA8PSoCri0',
    appId: '1:512093449312:web:31a460bc805c722655e705',
    messagingSenderId: '512093449312',
    projectId: 'flutter-notes-app-5f2d2',
    authDomain: 'flutter-notes-app-5f2d2.firebaseapp.com',
    storageBucket: 'flutter-notes-app-5f2d2.firebasestorage.app',
    measurementId: 'G-C2K8C3B82D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFuW34ytREeAm_CTKuRfhCFVT8BovhJC4',
    appId: '1:512093449312:android:fabc8ab23bd2ecf555e705',
    messagingSenderId: '512093449312',
    projectId: 'flutter-notes-app-5f2d2',
    storageBucket: 'flutter-notes-app-5f2d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVVA5LksNUNJ-oeq3CJKuMj25OJJRGexU',
    appId: '1:512093449312:ios:f67816d5e108e3bf55e705',
    messagingSenderId: '512093449312',
    projectId: 'flutter-notes-app-5f2d2',
    storageBucket: 'flutter-notes-app-5f2d2.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVVA5LksNUNJ-oeq3CJKuMj25OJJRGexU',
    appId: '1:512093449312:ios:f67816d5e108e3bf55e705',
    messagingSenderId: '512093449312',
    projectId: 'flutter-notes-app-5f2d2',
    storageBucket: 'flutter-notes-app-5f2d2.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8RQzJHNi8pUmqiAYcUrFU5sA8PSoCri0',
    appId: '1:512093449312:web:db30b201d9381cd755e705',
    messagingSenderId: '512093449312',
    projectId: 'flutter-notes-app-5f2d2',
    authDomain: 'flutter-notes-app-5f2d2.firebaseapp.com',
    storageBucket: 'flutter-notes-app-5f2d2.firebasestorage.app',
    measurementId: 'G-PPRZFQ2ZHZ',
  );

}